name=bgt60-radar-sensor
version=1.0.0
author=Infineon Technologies
maintainer=Infineon Technologies <www.infineon.com>
sentence=Arduino library for the Infineon BGT60TRxx radar sensor
paragraph=...
category=Device Control
url=https://github.com/Infineon/arduino-radar-bgt60tr13
architectures=*