name=bgt60tr13-radar-sensor
version=1.0.0
author=Infineon Technologies
maintainer=Infineon Technologies <www.infineon.com>
sentence=Arduino library for the Infineon BGT60TR13C radar sensor
paragraph=The chip consists of three receiver antennas and one transmit antenna.
category=Device Control
url=https://github.com/Infineon/arduino-radar-bgt60tr13
depends=arduinoFFT (>=2.0.0)
architectures=*