name=XENSIV BGT60TR13C Radar Sensor
version=0.1.0
author=Infineon Technologies
maintainer=Infineon Technologies <www.infineon.com>
sentence=Arduino library for the Infineon XENSIV BGT60TR13C radar sensor
paragraph=The BGT60TR13C is a 60 GHz radar sensor with Antennas in Package (AIP) in an L-shaped array. Its built-in Finite-State Machine (FSM) manages FMCW frequency sweeps, data acquisition, and sample storage into the internal FIFO memory, while optimized power modes and DC duty cycling minimize power consumption. The sensor is configured and controlled via a standard SPI interface, allowing for easy integration into various applications.
category=Sensors
url=https://github.com/Infineon/arduino-xensiv-radar-sensor-bgt60tr13
depends=arduinoFFT (>=2.0.0)
architectures=*